version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_delivery_food
    restart: always
    environment:

      MYSQL_ROOT_PASSWORD: admin

      MYSQL_DATABASE: pizzeria_
    ports:
      - "3306:3306"
    volumes:

      - ./mysql/init:/docker-entrypoint-initdb.d
      - optica_data:/var/lib/mysql

volumes:
  optica_data: